# Generated by Django 2.0.6 on 2018-06-20 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secim_metni', models.CharField(max_length=200)),
                ('oylar', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Soru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru_metni', models.CharField(max_length=200)),
                ('yayim_tarihi', models.DateTimeField(verbose_name='yayımlanma tarihi')),
            ],
        ),
        migrations.AddField(
            model_name='secim',
            name='soru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketler.Soru'),
        ),
    ]
